### ISSUE TITLE
addfleets command causes an exception when triggered on its own

### ISSUE THREAD

**Issue by randomic** [randomic/antinub-gregbot#11]
@steveizi

Trying
`!addfleets`
causes
```Python
Traceback (most recent call last):
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 822, in process_commands
    yield from command.invoke(ctx)
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 360, in invoke
    yield from self.prepare(ctx)
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 338, in prepare
    yield from self._parse_arguments(ctx)
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 297, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 205, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: fdate is a required argument that is missing.
```

**Comment by randomic** [comment]
Fixed by #13
