### ISSUE TITLE
Error in killmail retrieve loop:

### ISSUE THREAD

**Issue by randomic** [randomic/antinub-gregbot#16]
Should probably just log this and retry as normal

```Python
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/zyphore/antinub-gregbot/ext/killmails.py", line 55, in retrieve_kills
    package = await self.wait_for_package()
  File "/home/zyphore/antinub-gregbot/ext/killmails.py", line 85, in wait_for_package
    async with self.session.get(self.conf['redisQ_url']) as resp:
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client.py", line 565, in __aenter__
    self._resp = yield from self._coro
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client.py", line 209, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
```

**Comment by randomic** [comment]
Error in killmail retrieve loop:
```Python
Traceback (most recent call last):
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/zyphore/antinub-gregbot/ext/killmails.py", line 55, in retrieve_kills
    package = await self.wait_for_package()
  File "/home/zyphore/antinub-gregbot/ext/killmails.py", line 85, in wait_for_package
    async with self.session.get(self.conf['redisQ_url']) as resp:
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client.py", line 565, in __aenter__
    self._resp = yield from self._coro
  File "/home/zyphore/antinub-gregbot/venv/lib/python3.5/site-packages/aiohttp/client.py", line 209, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError
```
